import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  Dimensions, ActivityIndicator, Alert, StatusBar, Platform
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import axios from 'axios';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { translations } from '../utils/translations';
import BottomNavBar from '../components/BottomNavBar'; // ✅ Import global navbar

const { width } = Dimensions.get('window');
const THEME_COLOR = '#2D7D46';

// ✅ FIXED: Changed to 10.0.2.2 for Android Emulator stability
const API_BASE_URL = 'http://10.0.2.2:8000/api/v1';

const ProfileScreen = ({ navigation }) => {
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const [lang, setLang] = useState('en');

  useEffect(() => {
    fetchProfileData();
    const unsubscribe = navigation.addListener('focus', () => {
      fetchProfileData();
    });
    return unsubscribe;
  }, [navigation]);

  const fetchProfileData = async () => {
    try {
      const username = await AsyncStorage.getItem('userName');
      const savedLang = await AsyncStorage.getItem('userLang') || 'en';
      setLang(savedLang);

      if (!username) {
        navigation.replace('Login');
        return;
      }

      // Fetching profile data from Django Backend
      const response = await axios.get(`${API_BASE_URL}/get-profile/?username=${username}`, {
        timeout: 10000
      });
      setProfile(response.data);
    } catch (error) {
      console.error("Profile Connection Error:", error.message);
      // Optional: Alert.alert("Connection Error", "Could not reach Sanjeevani servers.");
    } finally {
      setLoading(false);
    }
  };

  const toggleLanguage = async () => {
    const newLang = lang === 'en' ? 'hi' : 'en';
    setLang(newLang);
    await AsyncStorage.setItem('userLang', newLang);
  };

  const handleDownloadReport = async () => {
    if (!profile) return;

    // Custom PDF template for the health report
    const htmlContent = `
      <html>
        <body style="font-family: Helvetica; padding: 40px;">
          <h1 style="color: ${THEME_COLOR}; text-align: center;">Sanjeevani AI Health Report</h1>
          <hr/>
          <div style="margin-top: 20px;">
            <p style="font-size: 18px;"><b>User Name:</b> ${profile.username}</p>
            <p style="font-size: 18px;"><b>Body Prakriti:</b> ${profile.prakriti || 'Not Analyzed'}</p>
            <p style="font-size: 18px;"><b>Age:</b> ${profile.age}</p>
            <p style="font-size: 18px;"><b>Gender:</b> ${profile.gender}</p>
          </div>
          <br/><br/>
          <p style="font-size: 12px; color: gray; text-align: center;">Generated by Sanjeevani Ayurvedic Recommender System</p>
          <p style="font-size: 12px; color: gray; text-align: center;">Date: ${new Date().toLocaleDateString()}</p>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html: htmlContent });
      await Sharing.shareAsync(uri);
    } catch (error) {
      Alert.alert("Export Failed", "Could not generate PDF.");
    }
  };

  const handleLogout = () => {
    Alert.alert(
      lang === 'hi' ? "लॉगआउट" : "Logout",
      lang === 'hi' ? "क्या आप बाहर निकलना चाहते हैं?" : "Exit Sanjeevani?",
      [
        { text: lang === 'hi' ? "नहीं" : "No", style: "cancel" },
        { text: lang === 'hi' ? "हाँ" : "Yes", style: "destructive", onPress: async () => {
            await AsyncStorage.clear();
            navigation.reset({ index: 0, routes: [{ name: 'Login' }] });
        }}
      ]
    );
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={THEME_COLOR} />
      </View>
    );
  }

  const t = translations[lang];

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor={THEME_COLOR} />

      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} hitSlop={{top:10, bottom:10, left:10, right:10}}>
          <Text style={styles.backArrow}>←</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>{t.profile}</Text>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.avatarSection}>
          <View style={styles.avatarCircle}>
             <Text style={styles.avatarSymbol}>🧘</Text>
          </View>
          <Text style={styles.welcomeName}>{profile?.username || 'User'}</Text>
          <View style={styles.doshaTagBox}>
             <Text style={styles.doshaTag}>{profile?.prakriti || "Dosha Not Set"}</Text>
          </View>
        </View>

        <View style={styles.infoContainer}>
          <ProfileInfoCard label="Email" value={profile?.email || 'N/A'} icon="✉️" />
          <ProfileInfoCard label="Details" value={`${profile?.age} yrs | ${profile?.gender}`} icon="👤" />

          <Text style={styles.menuLabel}>Quick Actions</Text>

          <TouchableOpacity style={styles.menuItem} onPress={() => navigation.navigate('DoshaQuiz')}>
            <View style={[styles.menuIconBox, {backgroundColor: '#FFF8E1'}]}><Text>🧭</Text></View>
            <Text style={styles.menuText}>Retake Prakriti Quiz</Text>
            <Text style={styles.arrow}>➔</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.menuItem} onPress={handleDownloadReport}>
            <View style={[styles.menuIconBox, {backgroundColor: '#E3F2FD'}]}><Text>📥</Text></View>
            <Text style={styles.menuText}>Download Health PDF</Text>
            <Text style={styles.arrow}>➔</Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.menuItem} onPress={() => navigation.navigate('About')}>
            <View style={[styles.menuIconBox, {backgroundColor: '#F3E5F5'}]}><Text>ℹ️</Text></View>
            <Text style={styles.menuText}>About Sanjeevani</Text>
            <Text style={styles.arrow}>➔</Text>
          </TouchableOpacity>
        </View>

        <TouchableOpacity style={styles.logoutButton} onPress={handleLogout}>
          <Text style={styles.logoutText}>Logout</Text>
        </TouchableOpacity>

        {/* ✅ Increased padding to ensure the logout button isn't hidden behind the navbar */}
        <View style={{ height: 120 }} />
      </ScrollView>

      {/* ✅ Add the global Bottom Nav Bar here */}
      <BottomNavBar navigation={navigation} activeScreen="Profile" />

    </View>
  );
};

const ProfileInfoCard = ({ label, value, icon }) => (
  <View style={styles.infoCard}>
    <View style={styles.iconBox}><Text style={{fontSize: 20}}>{icon}</Text></View>
    <View style={styles.textDetails}>
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.infoValue}>{value}</Text>
    </View>
  </View>
);

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8FAF8' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 15, paddingTop: Platform.OS === 'ios' ? 50 : StatusBar.currentHeight + 10,
    paddingBottom: 15, backgroundColor: THEME_COLOR, elevation: 8
  },
  backArrow: { color: '#FFF', fontSize: 30, fontWeight: 'bold' },
  headerTitle: { color: '#FFF', fontSize: 20, fontWeight: 'bold' },
  langBadge: { backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: '#FFF' },
  langText: { color: '#FFF', fontWeight: 'bold', fontSize: 12 },
  scrollContent: { paddingHorizontal: 20 },
  avatarSection: { alignItems: 'center', marginVertical: 30 },
  avatarCircle: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#FFF', justifyContent: 'center', alignItems: 'center', elevation: 4 },
  avatarSymbol: { fontSize: 45 },
  welcomeName: { fontSize: 22, fontWeight: 'bold', color: '#1B5E20' },
  doshaTagBox: { backgroundColor: THEME_COLOR, paddingHorizontal: 18, paddingVertical: 5, borderRadius: 20, marginTop: 10 },
  doshaTag: { color: '#FFF', fontWeight: 'bold', fontSize: 12 },
  infoContainer: { gap: 15 },
  menuLabel: { fontSize: 14, fontWeight: 'bold', color: '#888', marginTop: 15, marginBottom: 5 },
  infoCard: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 15, padding: 15, alignItems: 'center', borderWidth: 1, borderColor: '#EEE', elevation: 2 },
  iconBox: { width: 45, height: 45, borderRadius: 12, backgroundColor: '#F1F8E9', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  textDetails: { flex: 1 },
  infoLabel: { fontSize: 11, color: '#AAA' },
  infoValue: { fontSize: 15, fontWeight: 'bold', color: '#333' },
  menuItem: { flexDirection: 'row', backgroundColor: '#FFF', borderRadius: 15, padding: 15, alignItems: 'center', borderWidth: 1, borderColor: '#EEE', elevation: 2 },
  menuIconBox: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#F5F5F5', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  menuText: { flex: 1, fontWeight: '600', color: '#444' },
  arrow: { color: THEME_COLOR, fontWeight: 'bold' },
  logoutButton: { marginTop: 30, padding: 16, borderRadius: 15, borderWidth: 1.5, borderColor: '#FF5252', alignItems: 'center' },
  logoutText: { color: '#FF5252', fontWeight: 'bold' },
});

export default ProfileScreen;