# Generated by Django 3.2.25 on 2026-01-10 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('input_symptoms', models.TextField(help_text='Comma-separated symptom IDs')),
                ('dosha_at_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='remedy',
            old_name='details',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='dosha_imbalance',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='title',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='treats_diseases',
        ),
        migrations.AddField(
            model_name='disease',
            name='diet_plan',
            field=models.TextField(default='Consult an Ayurvedic practitioner for a personalized diet.', help_text='Recommended Ayurvedic diet for this condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='dosha_type',
            field=models.CharField(choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha'), ('Tridoshic', 'Tridoshic'), ('Vata-Pitta', 'Vata-Pitta'), ('Pitta-Kapha', 'Pitta-Kapha'), ('Vata-Kapha', 'Vata-Kapha')], default='Tridoshic', max_length=50),
        ),
        migrations.AddField(
            model_name='disease',
            name='remedies',
            field=models.ManyToManyField(related_name='diseases', to='recommender_api.Remedy'),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity_level',
            field=models.CharField(default='Mild', max_length=50),
        ),
        migrations.AddField(
            model_name='remedy',
            name='name',
            field=models.CharField(default='Unnamed Remedy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedy',
            name='precaution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='preparation',
            field=models.TextField(blank=True, help_text='How to use the remedy', null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='recommender_api.Symptom'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='body_system',
            field=models.CharField(help_text='e.g., Digestive, Respiratory', max_length=100),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
