# Generated by Django 3.2.25 on 2026-01-20 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender_api', '0002_auto_20260110_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhealthlog',
            options={},
        ),
        migrations.RenameField(
            model_name='userhealthlog',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='severity_level',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='precaution',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='body_system',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='description',
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disease',
            name='sanskrit_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='remedy',
            name='dosage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='remedy',
            name='sanskrit_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='remedy',
            name='usage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='disease',
            name='diet_plan',
            field=models.TextField(help_text='Recommended Ayurvedic diet for this condition.'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='dosha_type',
            field=models.CharField(choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha'), ('Tridoshic', 'Tridoshic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='remedy',
            name='preparation',
            field=models.TextField(blank=True, default='Standard Preparation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhealthlog',
            name='input_symptoms',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userhealthlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_dosha', models.CharField(default='Unknown', max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
