# Generated by Django 3.2.25 on 2026-02-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_api', '0003_auto_20260120_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='base_dosha',
            new_name='prakriti',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
